### ISSUE TITLE
Support Cocoapods

### ISSUE THREAD

**Issue by hernangonzalez** [Cosmo/TinyConsole#1]
Hello,

Nice doing here. Are you planning on creating a pod for it?

Thanks,
H.

**Comment by Cosmo** [comment]
Didn't plan to do it, but why not. I'm on it! :)

**Comment by Cosmo** [comment]
Done. @hernangonzalez
TinyConsole is now available via `pod 'TinyConsole'`.

Please let me know if that works for you, so I can close this issue.

**Comment by hernangonzalez** [comment]
Thanks @Cosmo , that worked great 🎉

**Comment by Cosmo** [comment]
Thanks for your suggestion and testing! 🎉
