### ISSUE TITLE
iOS 8 support

### ISSUE THREAD

**Issue by lianweiqin** [Cosmo/TinyConsole#15]
I noticed that iOS 8 is supported now, but in the .podspec file :
```
s.ios.deployment_target = '9.0'
```
is still 9.0...

Please update the CocoaPod repo,  THX : )

**Comment by mRs-** [comment]
opened https://github.com/Cosmo/TinyConsole/pull/18 for it

**Comment by mRs-** [comment]
@Cosmo you must take the next action to publish it via cocoapods

**Comment by Cosmo** [comment]
It's fixed now and released as 1.3.2. Thanks!
