### ISSUE TITLE
ios 8 support

### ISSUE THREAD

**Issue by aixinyunchou** [Cosmo/TinyConsole#2]
please support ios8

**Comment by wangguangfeng** [comment]
Yes. I need support ios8 too. Thank you

**Comment by Cosmo** [comment]
The only thing that prevents downgrading to iOS 8 is the Auto Layout Layout Anchor API (which is really nice!).

Would you mind to create a pull request?

**Comment by wangguangfeng** [comment]
I have created a pull request
