### ISSUE TITLE
 Mirroring XCode Console

### ISSUE THREAD

**Issue by filippocld** [Cosmo/TinyConsole#22]
I am quite a beginner in swift and objc, but is there a way to completely mirror what's shown in the Xcode Console?

**Comment by gallowsxbird** [comment]
For now, you can use TinyConsole and set the global paramter to true. This will log your message to both the TinyConsole and the Xcode Console.

**Comment by filippocld** [comment]
Thanks anyway :-/

**Comment by mRs-** [comment]
IMHO this would be an awesome addition to TinyConsole, but at the moment this is not supported and was not intended from @Cosmo in the beginning.

The easiest way for you would be to replace your logs with the TinyConsole method with global = true
