### ISSUE TITLE
Have you changed the api?

### ISSUE THREAD

**Issue by PandaraWen** [Cosmo/TinyConsole#32]
I can not find `createViewController` in any place, with TinyConsole v1.3.2

**Comment by Janscho** [comment]
Hi PandaraWen,

I got it working by using TinyConsoleController.init(rootViewController: window!.rootViewController!). Don't know why they didn't update the documentation.

**Comment by Cosmo** [comment]
Yeah, after some changes, the README was not updated. 
After over 1 year, I took the time to take care of it. Sorry! :)
