### ISSUE TITLE
Installation instructions are a little unclear

### ISSUE THREAD

**Issue by damienstanton** [Cosmo/TinyConsole#46]
Using XCode 11.4, Swift 5.2, and only either Swift Package Manager or manual framework install (we do not use Carthage nor Cocoapods), how do we install TinyConsole?

Building from source and importing the Swift module does not work, "just including the sources" as suggested in the README also does not work.

A minimal test case always throws the error `No such module 'TinyConsole'`. What's the correct way to include this library?

**Comment by Cosmo** [comment]
Just checking in: Did you run into issues?

**Comment by damienstanton** [comment]
I think there was an issue with the frameworks search path in this specific case. I don't think anything else needs to be done. Thanks!
