### ISSUE TITLE
Coloured output

### ISSUE THREAD

**Issue by jyounus** [Cosmo/TinyConsole#6]
Hey there,

It would be really cool if it would support coloured text output. So for an error it'll be red, warning orange etc. Colours which I can manually define. Not sure if that would be an overkill, but I would welcome it. 

Something like this would be good enough for my purposes (the 'color' parameter being optional and defaulting to nil):
```
TinyConsole.print("hello", color: UIColor.red)
```

Thanks

**Comment by gallowsxbird** [comment]
I'm on it. :)

**Comment by gallowsxbird** [comment]
Would you like the whole line to be coloured or just the text you want to print ?

**Comment by jyounus** [comment]
Nice! :D

How about having a global var which we can set?

I personally would prefer just the text, so that when it goes onto a new line, I can easily identify it because of the white datetime text.

**Comment by gallowsxbird** [comment]
The global var would be the text color of all the text in TinyConsole or what would it do?

**Comment by jyounus** [comment]
I meant having a global var for your preference if you want to colour the whole line or just the text I provided. 

So something like ```TinyConsole.colorizeWholeLine = true``` would colour the whole line. If set to false, it would only colour the text I provided.

What do you think? Would be great to give devs the option to select whatever they prefer. :)

**Comment by Cosmo** [comment]
How about we set the texts as attributed strings?

**Comment by gallowsxbird** [comment]
@Cosmo See my fork.

**Comment by Cosmo** [comment]
Oh :D I Just took a look on the `TinyConsole.swift` file.
I think its sufficient to only have `text: String` as a valid parameter for texts.
By adding the `color: UIColor` parameter you set the color anyway.

What do you think?

**Comment by gallowsxbird** [comment]
I think it would be nice to have a function that also prints NSFormattedStrings since we have implemented the functionality anyways. 

You could use your own custom fonts, colours, whatever you like for a really special console output message. 😄
